INSERT INTO "public"."unisum_category" VALUES ('1', 'LENGTH', 'distance');
INSERT INTO "public"."unisum_category" VALUES ('2', 'PRESSURE or STRESS (FORCE DIVIDED BY AREA)', 'pressure');
INSERT INTO "public"."unisum_category" VALUES ('3', 'VOLUME (includes CAPACITY)', 'volume');
INSERT INTO "public"."unisum_category" VALUES ('4', 'Heat Flow Rate', 'power');
INSERT INTO "public"."unisum_category" VALUES ('5', 'TIME', 'time');
INSERT INTO "public"."unisum_category" VALUES ('6', 'MASS and MOMENT OF INERTIA', 'mass_and_weight');
INSERT INTO "public"."unisum_category" VALUES ('7', 'Angular Velocity', 'angular_velocity');
INSERT INTO "public"."unisum_category" VALUES ('8', 'VOLUME DIVIDED BY TIME', 'flow_rate');
INSERT INTO "public"."unisum_category" VALUES ('9', 'MASS DIVIDED BY TIME (includes FLOW)', 'flow_rate_by_mass');
INSERT INTO "public"."unisum_category" VALUES ('10', 'MASS DIVIDED BY VOLUME', 'density');
INSERT INTO "public"."unisum_category" VALUES ('11', 'VISCOSITY, DYNAMIC', 'viscosity');
INSERT INTO "public"."unisum_category" VALUES ('12', 'AREA AND SECOND MOMENT OF AREA', 'area');
INSERT INTO "public"."unisum_category" VALUES ('13', 'MOMENT OF FORCE or TORQUE', 'torque');
INSERT INTO "public"."unisum_category" VALUES ('14', 'SPEED', 'speed');
INSERT INTO "public"."unisum_category" VALUES ('15', 'TEMPERATURE', 'temperature');
INSERT INTO "public"."unisum_category" VALUES ('16', 'PERMEABILITY', 'permeability');
INSERT INTO "public"."unisum_category" VALUES ('17', 'Transmissibility', 'transmissibility');
INSERT INTO "public"."unisum_category" VALUES ('18', 'Transmissivity', 'transmissivity');
INSERT INTO "public"."unisum_category" VALUES ('19', 'Сompressibility', 'compressibility');
INSERT INTO "public"."unisum_category" VALUES ('20', 'Pressure Diffusivity', 'pressure_diffusivity');
INSERT INTO "public"."unisum_category" VALUES ('21', 'Porosity', 'porosity');
INSERT INTO "public"."unisum_category" VALUES ('22', 'Wellbore Storage', 'wellbore_storage');
INSERT INTO "public"."unisum_category" VALUES ('23', 'Gravity', 'gravity');
INSERT INTO "public"."unisum_category" VALUES ('24', 'Gas Oil Ratio', 'gas_oil_ratio');
INSERT INTO "public"."unisum_category" VALUES ('25', 'Salinity', 'salinity');
INSERT INTO "public"."unisum_category" VALUES ('26', 'Formation Volume Factor Fluid', 'formation_volume_factor_fluid');
INSERT INTO "public"."unisum_category" VALUES ('27', 'Solid angle', 'solid_angle');
INSERT INTO "public"."unisum_category" VALUES ('28', 'Thermal conductivity', 'thermal_conductivity');
INSERT INTO "public"."unisum_category" VALUES ('29', 'Heat capacity', 'heat_capacity');
INSERT INTO "public"."unisum_category" VALUES ('30', 'Dimensionless', 'dimensionless');
INSERT INTO "public"."unisum_category" VALUES ('31', 'FORCE DIVIDED BY LENGTH', 'surface_tension');
INSERT INTO "public"."unisum_category" VALUES ('32', 'Dense', 'dense');
INSERT INTO "public"."unisum_category" VALUES ('33', 'Zg', 'zg');
INSERT INTO "public"."unisum_category" VALUES ('34', 'Water Cut', 'water_cut');
INSERT INTO "public"."unisum_category" VALUES ('35', 'Noise', 'noise');
INSERT INTO "public"."unisum_category" VALUES ('36', 'INVERSELABTIME', 'inverselabtime');
INSERT INTO "public"."unisum_category" VALUES ('37', 'Pseudo Pressure', 'pseudopressure');
INSERT INTO "public"."unisum_category" VALUES ('38', 'GorRsRation', 'gor_rs_ration');
INSERT INTO "public"."unisum_category" VALUES ('39', 'Productivity', 'productivity');
INSERT INTO "public"."unisum_category" VALUES ('40', 'Pressure Transient Response', 'pressure_transient_response');
INSERT INTO "public"."unisum_category" VALUES ('41', 'Rate Skin Depended', 'rate_depended_skin');